language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t montassarfatfouti/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true montassarfatfouti/react-test npm test

after_success:
  - docker build -t montassarfatfouti/multi-client ./client
  - docker build -t montassarfatfouti/multi-nginx ./nginx
  - docker build -t montassarfatfouti/multi-server ./server
  - docker build -t montassarfatfouti/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push montassarfatfouti/multi-client
  - docker push montassarfatfouti/multi-nginx
  - docker push montassarfatfouti/multi-server
  - docker push montassarfatfouti/multi-worker
